#!/usr/bin/env bash

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# $DRUDE_PATH is path to .drude folder. It is passed down from dsh to any custom command
DOCROOT='docroot'
DOCROOT_PATH="$DRUDE_PATH/$DOCROOT"
# Set to the appropriate site directory
SITE_DIRECTORY='default'
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
# Set to the appropriate site domain
SITE_DOMAIN='drupal8.drude'

#-------------------------- END: Settings --------------------------------


#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

if_failed ()
{
	if [ ! $? -eq 0 ]; then
		if [[ "$1" == "" ]]; then msg="an error occurred"; else msg="$1"; fi
		echo-red "$msg";
		exit 1;
	fi
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
    local source="$1"
    local dest="$2"

    if [[ ! -f $dest ]]; then
        echo-green "Copying ${dest}..."
        cp $source $dest
    else
        echo-yellow "${dest} already in place."
    fi
}

#-------------------------- END: Helper functions --------------------------------


#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
    # Copy from settings templates
    copy_settings_file "${DRUDE_PATH}/.drude/drude-local.yml" "${DRUDE_PATH}/docker-compose.yml"
    copy_settings_file "${SITEDIR_PATH}/example.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Set file/folder permissions
file_permissions ()
{
    mkdir -p $DOCROOT_PATH/sites/$SITE_DIRECTORY/files
    chmod 777 $DOCROOT_PATH/sites/$SITE_DIRECTORY/files
}

# Install site
site_install ()
{
    cd "$DOCROOT_PATH" && \
    dsh exec drush8 si -y --site-name="My Drupal 8 Site"
}

#-------------------------- END: Functions --------------------------------


#-------------------------- Execution --------------------------------

if [[ "$DRUDE_PATH" == "" ]]; then
	echo-red "\$DRUDE_PATH is not set"
	exit 1
fi

echo -e "${green_bg} Step 1 ${NC}${green} Initializing local project configuration...${NC}"
init_settings

#echo-green "Setting file/folder permissions..."
#file_permissions

echo -e "${green_bg} Step 2 ${NC}${green} Recreating services...${NC}"
dsh reset
# Give MySQL some time to start
echo-green "Waiting 10s for MySQL to start...";
sleep 10

echo -e "${green_bg} Step 3 ${NC}${green} Installing site...${NC}"
time site_install

echo -e "${green_bg} DONE! ${NC}"
echo -e "Open ${yellow}http://${SITE_DOMAIN}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
